Fix UB in QXmppTransferManager when parsing stream features
qxmpp-project/qxmpp pull request #322
Opened 2020-12-07 14:29 UTC by lichtzeichner

`featureForm()` returns a `QXmppDataForm` by value - directly taking a reference to a member of this class is undefined behavior and leads to a crash.

This PR changes the code to take references to both the form and the fields inside, thus extending the lifetime to the end of the function, fixing said crash.

2020-12-07 16:14 UTC, 0xd34df00d commented
Great catch, thanks!

The root cause seems to be that in `iq.featureForm().fields();`, the non-`const` overload of `fields()` is used which returns a (non-`const`) reference to the member, so the rules of lifetime extension don't apply.

2020-12-07 16:14 UTC, 0xd34df00d approved these changes

2020-12-07 20:24 UTC, lnjX requested changes
Great! Could you change the base branch of the PR to `1.3`? So if we create a v1.3.2 it'll be in there.

2020-12-08 07:29 UTC, lichtzeichner commented
@InjX: there you go. I hope I rebased the right way, but the diff looks good.

2020-12-11 16:56 UTC, lnjX approved these changes
Thank you very much! :)

2020-12-11 16:58 UTC, merged