Implement XEP-0167: Jingle RTP Sessions SRTP negotiation
qxmpp-project/qxmpp pull request #487
Opened 2022-10-02 00:43 UTC by melvo

PR check list:
- [ ] Document your code
- [ ] Add `\since QXmpp 1.X`, `QXMPP_EXPORT`
- [ ] Fix doxygen warnings (see log when building with `-DBUILD_DOCUMENTATION=ON`)
- [ ] Update `doc/doap.xml`
- [ ] Add unit tests
- [ ] Format the code: Run `clang-format -i src/<edited-file(s)> tests/<edited-file(s)>`

2022-10-02 14:15 UTC, lnjX requested changes

2022-10-02 18:05 UTC, melvo commented on src/base/QXmppJingleIq.cpp
> +    uint32_t tag;
I did not initialize it because the XEP specifies no default value and 0 is a valid tag.

2022-10-02 18:11 UTC, melvo commented on src/base/QXmppJingleIq.cpp
> +    return element.tagName() == QStringLiteral("crypto");
The `crypto` element has no namespace.

2022-10-02 19:43 UTC, lnjX commented on src/base/QXmppJingleIq.cpp
> +    uint32_t tag;
If you don't initialize it then you'll get a random value (and random behaviour) that's definitely not better.

2022-10-03 10:48 UTC, melvo commented on src/base/QXmppJingleIq.cpp
> +    uint32_t tag;
I see.

2022-10-03 11:14 UTC, lnjX approved these changes

2022-10-03 11:14 UTC, merged