OmemoManagerPrivate: Fix device setup
qxmpp-project/qxmpp pull request #507
Opened 2022-10-26 19:58 UTC by melvo

PR check list:
- [x] Document your code
- [x] Add `\since QXmpp 1.X`, `QXMPP_EXPORT`
- [x] Fix doxygen warnings (see log when building with `-DBUILD_DOCUMENTATION=ON`)
- [x] Update `doc/doap.xml`
- [x] Add unit tests
- [x] Format the code: Run `clang-format -i src/<edited-file(s)> tests/<edited-file(s)>`

2022-10-29 16:30 UTC, melvo commented
This change is especially needed in order to set up OMEMO with Prosody.

2022-12-22 14:43 UTC, lnjX requested changes

2022-12-22 14:43 UTC, lnjX commented on src/omemo/QXmppOmemoManager_p.cpp
> +                    }
The error case / where `reportFinishedResult(interface, false);` is called is a bit hidden here and I don't think the helper function `generateDeviceId()` should be responsible for reporting the result of `setUpDeviceId()`.

2022-12-22 15:16 UTC, lnjX approved these changes

2022-12-22 15:17 UTC, merged